### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jzlianglu** [clab/dynet#129] opened 2016-10-26 15:04 UTC
I'm trying to install this toolkit but have the following problems. Note that I have installed the development version of Eigien as hg clone https://bitbucket.org/eigen/eigen/. 

[llu@cpu0 build]$ cmake .. -DEIGEN3_INCLUDE_DIR=./eigen -DBOOST_ROOT:PATHNAME=/home-nfs/llu/boost160 -DBoost_NO_BOOST_CMAKE=TRUE -DBoost_NO_SYSTEM_PATHS=TRUE -DBoost_LIBRARY_DIRS:FILEPATH=/home-nfs/llu/boost160/lib/

-- The C compiler identification is GNU 4.8.5

-- The CXX compiler identification is GNU 4.8.5

-- Check for working C compiler: /usr/bin/cc

-- Check for working C compiler: /usr/bin/cc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Check for working CXX compiler: /usr/bin/c++

-- Check for working CXX compiler: /usr/bin/c++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Boost dir is 

-- Boost version: 1.60.0

-- Found the following Boost libraries:

--   program_options

--   regex

--   serialization

-- BACKEND not specified, defaulting to eigen.

-- Eigen dir is /home-nfs/llu/dynet/eigen

-- Looking for include file pthread.h

-- Looking for include file pthread.h - found

-- Looking for pthread_create

-- Looking for pthread_create - not found

-- Looking for pthread_create in pthreads

-- Looking for pthread_create in pthreads - not found

-- Looking for pthread_create in pthread

-- Looking for pthread_create in pthread - found

-- Found Threads: TRUE  

-- Boost version: 1.60.0

-- Found the following Boost libraries:

--   system

--   filesystem

--   unit_test_framework

-- Configuring done

-- Generating done

-- Build files have been written to: /home-nfs/llu/dynet/build

[llu@cpu0 build]$ make -j 4

Scanning dependencies of target dynet

[  3%] [  3%] [  5%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o

Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o

[  7%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o

Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o

[  8%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o

[ 10%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o

[ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o

[ 14%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o

[ 16%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o

[ 17%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o

[ 19%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o

[ 21%] Building CXX object dynet/CMakeFiles/dynet.dir/graph.cc.o

[ 23%] Building CXX object dynet/CMakeFiles/dynet.dir/gru.cc.o

[ 25%] Building CXX object dynet/CMakeFiles/dynet.dir/hsm-builder.cc.o

[ 26%] Building CXX object dynet/CMakeFiles/dynet.dir/init.cc.o

[ 28%] Building CXX object dynet/CMakeFiles/dynet.dir/lstm.cc.o

[ 30%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o

[ 32%] Building CXX object dynet/CMakeFiles/dynet.dir/model.cc.o

[ 33%] Building CXX object dynet/CMakeFiles/dynet.dir/mp.cc.o

[ 35%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes.cc.o

[ 37%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-common.cc.o

[ 39%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-contract.cc.o

[ 41%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv.cc.o

[ 42%] Building CXX object dynet/CMakeFiles/dynet.dir/param-nodes.cc.o

[ 44%] Building CXX object dynet/CMakeFiles/dynet.dir/pretrain.cc.o

[ 46%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn.cc.o

[ 48%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn-state-machine.cc.o

[ 50%] Building CXX object dynet/CMakeFiles/dynet.dir/saxe-init.cc.o

[ 51%] Building CXX object dynet/CMakeFiles/dynet.dir/shadow-params.cc.o

[ 53%] Building CXX object dynet/CMakeFiles/dynet.dir/tensor.cc.o

[ 55%] Building CXX object dynet/CMakeFiles/dynet.dir/training.cc.o

[ 57%] Building CXX object dynet/CMakeFiles/dynet.dir/weight-decay.cc.o

Linking CXX shared library libdynet.so

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm_blend_ps':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:193: multiple definition of `Eigen::internal::eigen_packet_wrapper<float __vector> Eigen::internal::pinsertlast<Eigen::internal::eigen_packet_wrapper<float __vector> >(Eigen::internal::eigen_packet_wrapper<float __vector> const&, Eigen::internal::unpacket_traits<Eigen::internal::eigen_packet_wrapper<float __vector> >::type)'

CMakeFiles/dynet.dir/cfsm-builder.cc.o:(.text+0x750): first defined here

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm_blend_ps':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:193: multiple definition of `Eigen::internal::eigen_packet_wrapper<float __vector(4)> Eigen::internal::pinsertlast<Eigen::internal::eigen_packet_wrapper<float __vector(4)> >(Eigen::internal::eigen_packet_wrapper<float __vector(4)> const&, Eigen::internal::unpacket_traits<Eigen::internal::eigen_packet_wrapper<float __vector(4)> >::type)'

CMakeFiles/dynet.dir/cfsm-builder.cc.o:(.text+0x750): first defined here

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm_blend_pd':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:218: multiple definition of `Eigen::internal::eigen_packet_wrapper<double __vector> Eigen::internal::pinsertlast<Eigen::internal::eigen_packet_wrapper<double __vector> >(Eigen::internal::eigen_packet_wrapper<double __vector> const&, Eigen::internal::unpacket_traits<Eigen::internal::eigen_packet_wrapper<double __vector> >::type)'

CMakeFiles/dynet.dir/cfsm-builder.cc.o:(.text+0x760): first defined here

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm_blend_pd':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:218: multiple definition of `Eigen::internal::eigen_packet_wrapper<double __vector(2)> Eigen::internal::pinsertlast<Eigen::internal::eigen_packet_wrapper<double __vector(2)> >(Eigen::internal::eigen_packet_wrapper<double __vector(2)> const&, Eigen::internal::unpacket_traits<Eigen::internal::eigen_packet_wrapper<double __vector(2)> >::type)'

CMakeFiles/dynet.dir/cfsm-builder.cc.o:(.text+0x760): first defined here

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm256_blend_ps':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/avxintrin.h:181: multiple definition of `float __vector Eigen::internal::pinsertlast<float __vector>(float __vector const&, Eigen::internal::unpacket_traits<float __vector>::type)'

CMakeFiles/dynet.dir/cfsm-builder.cc.o:(.text+0x770): first defined here

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm256_blend_ps':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/avxintrin.h:181: multiple definition of `float __vector(8) Eigen::internal::pinsertlast<float __vector(8)>(float __vector(8) const&, Eigen::internal::unpacket_traits<float __vector(8)>::type)'

CMakeFiles/dynet.dir/cfsm-builder.cc.o:(.text+0x770): first defined here

CMakeFiles/dynet.dir/dynet.cc.o: In function `_mm256_blend_pd':

/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/avxintrin.h:173: multiple definition of `double __vector Eigen::internal::pinsertlast<double __vector>(double __vector const&, Eigen::internal::unpacket_traits<double __vector>::type)'

and many similar errors

**Comment by neubig** [comment] 2016-10-26 15:09
Thanks! We'll need to confirm this in our own environment, but this needs to be fixed.

**Comment by jpraher** [comment] 2016-10-31 23:04
I could reproduce the issue both with clang 3.8 and gcc 6.2.1, compiling and linking works fine when using eigen 3.3-rc1: http://bitbucket.org/eigen/eigen/get/3.3-rc1.tar.bz2

My CPU is an i7-3520M CPU w/ AVX vector extensions. 

It looks as if this is due to partially redundant VECTORIZED implementations. 
To testify I defined  EIGEN_DONT_VECTORIZE and then the development version of eigen version worked as well.

```
#if defined EIGEN_VECTORIZE_AVX
  // Use AVX for floats and doubles, SSE for integers
  #include "src/Core/arch/SSE/PacketMath.h"
  #include "src/Core/arch/SSE/Complex.h"
  #include "src/Core/arch/SSE/MathFunctions.h"
  #include "src/Core/arch/AVX/PacketMath.h"
  #include "src/Core/arch/AVX/MathFunctions.h"
  #include "src/Core/arch/AVX/Complex.h"
  #include "src/Core/arch/AVX/TypeCasting.h"

```

**Comment by jzlianglu** [comment] 2016-11-01 17:49
Yes, using this version of eigen, and a lower version of boots (v1.53) can solve this problem. Thanks for the reply.

**Comment by neubig** [comment] 2016-11-01 19:43
Hmm, this is a workaround but it'd be nice to have a fix. Could this be fixed by filing a bug report to the Eigen upstream? If so, it'd be great if you could create a minimal example and send it to them.

**Comment by neubig** [comment] 2017-04-07 20:40
I'm going to close this, as there seems to be a workaround above, and it's somewhat of a minority problem? Can reopen if it's still bugging people.

**Closed by neubig** 2017-04-07 20:40 UTC
Labels: moderate bug
