### ISSUE TITLE
how to use a specific initializer for VanillaLSTMBuilder?

### ISSUE THREAD

**Issue by rasoolims** [clab/dynet#636] opened 2017-06-27 17:39 UTC
I was not able to find an example. For example, how can I use a UniformInitializer with a specific stdv?

**Comment by pmichel31415** [comment] 2017-06-27 17:43
I don't think this is possible for now, although it would be cool if it were.

One solution is to set the value of the parameters manually after intialization.

If you are using python, something like:

    lstm=dy.VanillaLSTMBuilder(...)
    lstm.get_parameters()[0][0].set_value(np.random.uniform(...))

**Comment by pmichel31415** [comment] 2017-07-07 18:40
Actually this is a duplicate of #529

**Closed by pmichel31415** 2017-07-07 18:40 UTC
Labels: enhancement

**Comment by jcyk** [comment] 2017-07-21 07:25
@pmichel31415  I tried the way you suggested. It does seem to work on GPU. Any idea?
