### ISSUE TITLE
Example Code for TreeRNN

### ISSUE THREAD

**Issue by suwangcompling** [clab/dynet#387] opened 2017-03-19 16:10 UTC
I'm a linguist working in the space of discourse analysis, where TreeRNN (or TreeLSTM) is a promising tool. I was wondering by any chance you could post a piece of example code (Jupyter or anything) in the examples section?

Thanks.

**Comment by pmichel31415** [comment] 2017-03-19 18:24
I agree this should be added to the examples but for what it's worth there is code for a treenn in the benchmark repo here https://github.com/neulab/dynet-benchmark/tree/master/dynet-py

Is that what you're looking for?

**Comment by suwangcompling** [comment] 2017-03-19 18:56
Thanks michel! Yes this is helpful. 
Although, in my humble opinion commented code in Jupyter would further facilitate the dissemination of DyNet in the computational linguistics community. Currently there's tons more extensive tutorials on other libraries (Tensorflow, Theano, etc.), fitting to the need of users with a wide range of backgrounds. So it'd be nice to see the same documents for DyNet as an awesome architecture that excel at many tasks that the libs with static declaration cannot do (or awkward in implementation).

**Comment by pmichel31415** [comment] 2017-03-19 19:48
I agree with you, and we need all the help we can get, so all pull requests in this direction are appreciated.

In the meantime I'll close this as a duplicate of #191

**Closed by pmichel31415** 2017-03-19 19:48 UTC
Labels: duplicate, enhancement
