### ISSUE TITLE
Index of maximal element of an expression

### ISSUE THREAD

**Issue by xyda** [clab/dynet#1068] opened 2017-11-14 07:36 UTC
Is there an efficient operation function that gets the index of the maximal element of an expression? I noticed that max_dim function returns an expression of maximal elements. Can it also return the index?

**Comment by neubig** [comment] 2017-11-24 04:20
The recommended way of doing so is to just call:

`expr.npvalue().argmax()`

There's also some experimental functionality where you can directly call argmaxes on DyNet tensors without calling `npvalue()` here: https://github.com/clab/dynet/blob/49404127c5078af3f7c4c9d6d7628f324d36c2c0/python/_dynet.pyx#L1535

But we're currently working on a better way to do this, and the above experimental interface might change in the future.

**Comment by neubig** [comment] 2017-11-24 04:22
This is more or less a duplicate of #1067, so I'll close this to consolidate discussion there.

**Closed by neubig** 2017-11-24 04:22 UTC
