### ISSUE TITLE
can't initialize python RNN initial state

### ISSUE THREAD

**Issue by shaltielshmid** [clab/dynet#226] opened 2016-12-25 11:29 UTC
When initializing RNN state from vectors (`lstm.initial_state_from_raw_vectors`) or from expressions (`lstm.initial_state(state.s())`) things do not get initialized when a state was already initialized from this builder in the current computation graph. See example below.

```python

from dynet import *

m = Model()
lp = m.add_lookup_parameters((10, 10))
lstm = LSTMBuilder(2, 10, 10, m)
renew_cg()

state1 = lstm.initial_state() # works without this line
state2_new = lstm.initial_state_from_raw_vectors(tuple(np.ones(10) for _ in range(4)))
print state2_new.s()
```

**Comment by yoavg** [comment] 2016-12-25 11:30
Confirmed, this is a real bug.

**Comment by mitchellstern** [comment] 2016-12-25 15:12
I've encountered this behavior too, but thought it was an artifact of the underlying C++ `RNNBuilder` only supporting a single initial state per computation graph. I don't think you can call `start_new_sequence()` on an `RNNBuilder` multiple times within a single computation graph, since that clears the underlying state DAG of `RNNPointer`s and would lead to state index clashes.

In the meantime, a reasonable workaround seems to be using the `set_s()` method, which creates a new state with the given vectors:
```
>>> import numpy as np
>>> import dynet as dy
>>> model = dy.Model()
>>> lstm = dy.LSTMBuilder(2, 3, 3, model)

# Unintuitive current behavior
>>> dy.renew_cg()
>>> state1 = lstm.initial_state([dy.inputVector(np.zeros(3)) for i in range(4)])
>>> state2 = lstm.initial_state([dy.inputVector(np.ones(3)) for i in range(4)])
>>> [x.value() for x in state1.s()]
[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
>>> [x.value() for x in state2.s()]
[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

# Workaround
>>> dy.renew_cg()
>>> state1 = lstm.initial_state().set_s([dy.inputVector(np.zeros(3)) for i in range(4)])
>>> state2 = lstm.initial_state().set_s([dy.inputVector(np.ones(3)) for i in range(4)])
>>> [x.value() for x in state1.s()]
[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
>>> [x.value() for x in state2.s()]
[[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
```

**Comment by mitchellstern** [comment] 2016-12-25 15:25
Some possible alternatives to the current behavior might be:
  * Keep things as they are now, but issue a warning or raise an exception if the cached `self._init_state` being returned was created with a different `vecs` argument than the one passed to the current call of `initial_state()`.
  * Maintain an internal dummy root state, and allow for multiple effective initial states using a strategy like the above.

@yoavg: If you have a suggested fix, I have some time this week and could help submit a pull request addressing the issue.

**Comment by yoavg** [comment] 2016-12-25 16:14
thanks @mitchellstern ! I like the second option -- having an internal root state, and using set_s internally when vectors are requested. The user should not care about the weirdness of the underlying c++ implementation if possible.

**Comment by jeanm** [comment] 2017-09-07 13:27
Ran into this, and after much head scratching I luckily found this issue. Definitely agree there should at least be a warning.

**Comment by neubig** [comment] 2018-02-09 21:21
This should now be fixed by https://github.com/clab/dynet/pull/1228

**Closed by neubig** 2018-02-09 21:21 UTC
Labels: moderate bug
