### ISSUE TITLE
CURAND failure with CUDA 9

### ISSUE THREAD

**Issue by speedcell4** [clab/dynet#1274] opened 2018-03-06 07:19 UTC
I recompiled DyNet but got this

```bash
[moss100-(~)] python3.6
Python 3.6.1 (default, Apr  4 2017, 23:52:48)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynet
[dynet] random seed: 4058967311
CURAND failure in curandCreateGenerator(&curandeng, CURAND_RNG_PSEUDO_PHILOX4_32_10)
203
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  curandCreateGenerator(&curandeng, CURAND_RNG_PSEUDO_PHILOX4_32_10)
[1]    27548 abort      python3.6
```

for the version of CUDA

```bash
[moss100-(~)] nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

**Comment by sharidloaiciga** [comment] 2018-03-09 12:22
Currently having the same problem...

**Comment by speedcell4** [comment] 2018-03-09 12:36
It works well on CUDA 8.0

**Comment by sharidloaiciga** [comment] 2018-03-21 14:38
CUDA 8.0 + gcc 5.5 doesn't work either --> issue #1317 
https://github.com/clab/dynet/issues/1317

**Comment by akoehn** [comment] 2018-04-24 14:37
Can't reproduce this using cuda 9.0.176 and gcc 6.4.0, works for me since #1351.

**Comment by neubig** [comment] 2018-04-24 15:43
Yes, I also have no problem with CUDA 9. If anyone is still having trouble with this, please tell us.

**Comment by jyp** [comment] 2018-05-07 12:52
Appears to be fixed on master, thanks!

**Closed** 2018-05-07 15:32 UTC
Labels: fix needs confirmation
