### ISSUE TITLE
conv2d causes out-of-memory error in beam search

### ISSUE THREAD

**Issue by liesun1994** [clab/dynet#644] opened 2017-06-30 13:50 UTC
My beam search uses conv2d for tagging a long image sequence with beam size 10. It seems that conv2d accumulate the memory usage until the memory is used up. The error is as below:
![image](https://user-images.githubusercontent.com/16813308/27738489-0af16ad8-5dde-11e7-9e79-e3fb3820ab8b.png)

Can you provide a method for using conv2d in beam search mode? The out-of-memory error even with a small beam size will prevent the convolution computation in dynet.

**Comment by zhisbug** [comment] 2017-06-30 14:20
conv2d node will never call malloc or cudamalloc, it only uses the auxiliary memory when requesting memory. So it seems this is caused by the memory pool code? Is this relevant to the dynamic memory pool? @neubig

**Comment by neubig** [comment] 2017-06-30 14:28
Yes, this happens because the conv2d is allocating too much auxiliary memory. This issue is basically a duplicate of https://github.com/clab/dynet/issues/613 and https://github.com/clab/dynet/issues/577

I'll close the issue, but we should fix the conv2d memory problem.

**Closed by neubig** 2017-06-30 14:28 UTC
