### ISSUE TITLE
dynet-viz results in typeerror in call to trainer

### ISSUE THREAD

**Issue by emanjavacas** [clab/dynet#240] opened 2017-01-13 19:40 UTC
Whenever I switched on the `--dynet-viz` flag, I get following error:

```
Traceback (most recent call last):
  File "reverse.py", line 243, in <module>
    rnn.train(train_set, val_set)
  File "reverse.py", line 101, in train
    trainer = dy.SimpleSGDTrainer(self.model, lr, decay)
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
```
However the code runs normally otherwise.
Any hints?

**Comment by yoavg** [comment] 2017-01-13 20:16
The visualization mock code was not up-to-date with recent changes in trainer, should be fixed now.
Try and close the issue if it is indeed the case.

**Comment by emanjavacas** [comment] 2017-01-13 20:40
I rebuilt dynet (also the c++ library) and rerun it and that issue seems to be gone.
However another one shows up:

```
Traceback (most recent call last):
  File "test.py", line 276, in <module>
    train(encoder_decoder, train_set, val_set)
  File "test.py", line 33, in train
    loss = network.get_loss(input_string, output_string)
  File "test.py", line 235, in get_loss
    attended_encoding = self._attend(encoded_string, rnn_state)
  File "test.py", line 212, in _attend
    w2dt = w2 * state.h()[-1]
AttributeError: 'RNNState' object has no attribute 'h'
```

**Comment by yoavg** [comment] 2017-01-13 20:50
ok, the viz model definitely needs some love. I will look into it in the coming days.

(in case you are interested in how it works, dynet_viz.py has mock objects for all the components in DyNet, that don't perform any computation but instead know how to display themselves nicely. These need some updating because of some updates in DyNet that were not updated in the viz module)

**Comment by neubig** [comment] 2017-07-14 13:54
I think the dynet-viz module is now quite out-of-date. I think we need to either:
1. Update it now, and add it to the Python unit tests so Travis CI notifies us when it breaks in the future.
2. Remove the module altogether.

Any thoughts?

**Comment by neubig** [comment] 2018-02-09 21:20
Closed as duplicate of this https://github.com/clab/dynet/issues/157

**Closed by neubig** 2018-02-09 21:20 UTC
Labels: minor bug
