### ISSUE TITLE
dynet is out of memory, ....

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#132] opened 2016-10-28 12:07 UTC
DEBUG:nmt:each step lstm output => <type '_gdynet.Expression'> (32, 80)
dynet is out of memory, try increasing with --dynet-mem (current capacity: 1746927616)
run.sh: line 2: 20454               python $1 --dynet-gpu --dynet_mem 5000 --dynet-gpu-ids 2

i try to run a lstm model, but i always get above problem even i set --dynet_mem to be 5000m, i do not know why. can anyone help me to solve this problem ?

i print following information in `free()` function in `aligned-mem-pool.h`

```
freeing 0 bytes
freeing 1588306432 bytes
```

i am no sure whether it is regular that this memory value became larger and larger as training proceeds .

@pmichel31415 @neubig

**Comment by neubig** [comment] 2016-10-28 12:18
Duplicate of https://github.com/clab/dynet/issues/120

**Closed by neubig** 2016-10-28 12:18 UTC
