### ISSUE TITLE
segmentation fault at python: "import dynet"

### ISSUE THREAD

**Issue by chanansh** [clab/dynet#314] opened 2017-02-16 17:20 UTC
Hi,
I have followed the instructions here: http://dynet.readthedocs.io/en/latest/python.html
* Completion succeed.
* Running `example\train_xor` succeed.
* running `python setup.py install` finished.

Now, when I run `import dynet` in python I get segmentation fault.
I am using Docker with miniconda3
Tried also miniconda and ubuntu. 
Get the same result.

**Comment by neubig** [comment] 2017-02-16 17:26
Hi @chanansh, sorry. I just realized this bug too. This was introduced in a very recent version, and I'm working on fixing it, but for now the only solution is to revert to a previous version. Please try:

    git checkout 7f45b7e6b1dd85f510f7e6ce362dfd1e8942b52a

and re-do the installation instructions.

**Comment by pmichel31415** [comment] 2017-02-16 17:27
Is this on the latest version of dynet?

Also did you compile with cuda?

It might be linked to a pull request I made I'll take a look after lunch.

**Comment by neubig** [comment] 2017-02-16 17:32
@pmichel31415 I believe your intuition is correct, and this is not dependent on CUDA. I'm getting a segmentation fault here, even when compiling on CPU (Python 3.5).

     Invalid read of size 4
       at 0x79CF017: ??? (in /usr0/home/gneubig/usr/local/anaconda3/lib/libstdc++.so.6.0.19)
       by 0x79D0228: std::string::assign(std::string const&) (in /usr0/home/gneubig/usr/local/anaconda3/lib/libstdc++.so.6.0.19)
       by 0x6FFA588: operator= (basic_string.h:547)
       by 0x6FFA588: operator= (init.h:15)
       by 0x6FFA588: __pyx_f_6_dynet_11DynetParams_from_args(__pyx_obj_6_dynet_DynetParams*, int, __pyx_opt_args_6_dynet_11DynetParams_from_args*) (_dynet.cpp:4246)
       by 0x6FCDF0F: __pyx_pf_6_dynet_init (_dynet.cpp:5627)
       by 0x6FCDF0F: __pyx_pw_6_dynet_1init(_object*, _object*, _object*) (_dynet.cpp:5591)
       by 0x4EF3620: PyCFunction_Call (methodobject.c:98)
       by 0x4F7ABD4: call_function (ceval.c:4705)
       by 0x4F7ABD4: PyEval_EvalFrameEx (ceval.c:3236)
       by 0x4F7BB48: _PyEval_EvalCodeWithName (ceval.c:4018)
       by 0x4F7BCD7: PyEval_EvalCodeEx (ceval.c:4039)
       by 0x4F7BD1A: PyEval_EvalCode (ceval.c:777)
       by 0x4F6EDFD: builtin_exec_impl (bltinmodule.c:957)
       by 0x4F6EDFD: builtin_exec (bltinmodule.c.h:275)
       by 0x4EF35E8: PyCFunction_Call (methodobject.c:109)
       by 0x4F787BF: ext_do_call (ceval.c:5031)
       by 0x4F787BF: PyEval_EvalFrameEx (ceval.c:3275)
     Address 0xfffffffffffffff8 is not stack'd, malloc'd or (recently) free'd

It does not crash on my Mac for whatever reason. I'm taking a look now, but I'm not sure if I'll be able to fix before meetings.

Also, we should really get Travis CI testing of Python working as well: https://github.com/clab/dynet/issues/198

**Comment by chanansh** [comment] 2017-02-16 17:32
What version of eigen to use?

**Comment by chanansh** [comment] 2017-02-16 17:33
I compiled with CPU

**Comment by neubig** [comment] 2017-02-16 17:34
@chanansh The only way to fix the problem (that I know at the moment) is reverting the version of DyNet according to my instructions. The official version of Eigen recommended in the doc should work, both on CPU and GPU. Fixing this is top priority, so it should be fixed in the next couple hours.

**Comment by neubig** [comment] 2017-02-16 17:55
@chanansh @pmichel31415 This should be fixed in the master branch by this commit: https://github.com/clab/dynet/commit/5807b4364e237e135d025d335578e5c0211df4f0

Could you please try pulling the latest master and seeing if it works for you?

**Comment by pmichel31415** [comment] 2017-02-16 18:07
@neubig I'm about to test it now.

Do you think this could be linked to the python version? I used python 2.7 and had no bug, this had also been tested by someone else in #255

**Comment by neubig** [comment] 2017-02-16 18:20
@pmichel31415 This is quite possibly linked to the python version, yes.

**Comment by pmichel31415** [comment] 2017-02-16 18:29
So I wasn't able to reproduce this bug neither before nor after your patch @neubig . (tried on ubuntu CPU, both python 2.7 and 3.4

Looking at the error trace it looks like it could be a c++ problem.

@chanansh let me know if the patch solved it for you and/or if it works if you checkout 7f45b7e6b1dd85f510f7e6ce362dfd1e8942b52a

In the meantime i'll take a look. If the bug persists then I think it would be better to undo the pull request for now

**Comment by chanansh** [comment] 2017-02-16 19:19
7f45b7 resolved the issue

**Comment by neubig** [comment] 2017-02-16 20:42
@chanansh OK, if you have time to verify the latest version as well that would be greatly appreciated!

**Comment by neubig** [comment] 2017-02-21 05:07
This seems to be fixed, so I'll close it unless someone else can confirm it's broken.

**Closed by neubig** 2017-02-21 05:07 UTC
Labels: fix needs confirmation, major bug
