### ISSUE TITLE
Loading parameters from different files may NOT be correct?

### ISSUE THREAD

**Issue by jcyk** [clab/dynet#508] opened 2017-05-03 08:43 UTC
I encountered this problem in a real application. 
but, a simple example is given as follow.
```
import dynet as dy

m = dy.Model()
x = m.add_parameters((5))
y = m.add_parameters((5))

prev_x = x.as_array()
print prev_x
m.save('x', [x])

trainer = dy.SimpleSGDTrainer(m, 0.1)
px = dy.parameter(x)
py = dy.parameter(y)
pz = dy.dot_product(px ,py)
pz.backward()
trainer.update()

now_x = x.as_array()
print now_x
m.save('y',[y])
```
It saves the `x` before update and the `y` after update.
output: 
```
[-0.46507549 -0.35747367  1.03155005 -0.63845336  0.92313373]
[-0.56483394 -0.27518842  0.93067193 -0.66347545  0.9634636 ]
```
Then
```
import dynet as dy

m = dy.Model()
x, = m.load('x')
prev_x = x.as_array() 
y,  = m.load('y')
now_x = x.as_array()

print prev_x
print now_x
```

to restore the 'x' before update and the 'y' after update?
NO
output: 
```
[-0.46507549 -0.35747367  1.03155005 -0.63845336  0.92313373]
[-0.56483394 -0.27518842  0.93067193 -0.66347545  0.9634636 ]
```
It seems that loading the updated 'y' did an extra operation that is to rewrite `x` with the the updated 'x'

**Comment by neubig** [comment] 2017-05-05 12:39
I'm not exactly sure about the cause of this, but we're currently working on a revamp of model saving/loading that should make all of this clearer and easier to understand. We're hoping it should be ready in a week or so:
https://github.com/clab/dynet/issues/84

**Comment by neubig** [comment] 2017-06-29 01:38
This should be fixed by https://github.com/clab/dynet/pull/637

**Closed by neubig** 2017-06-29 01:38 UTC
Labels: moderate bug
