### ISSUE TITLE
error while testing ``python xor.py''

### ISSUE THREAD

**Issue by yuchenlin** [clab/dynet#649] opened 2017-07-01 05:58 UTC
Hi guys,

I just followed the install instruction in the new document for dynet2.0.
The installation was quite smooth. However, when I test my dynet with the ''python xor.py'', it says

`yuchen@statnlp0:~/dynet-base/dynet/examples/python$ python xor.py
Traceback (most recent call last):
  File "xor.py", line 2, in <module>
    import dynet as dy
  File "build/bdist.linux-x86_64/egg/dynet.py", line 17, in <module>
  File "build/bdist.linux-x86_64/egg/_dynet.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_dynet.py", line 6, in __bootstrap__
ImportError: /home/yuchen/.cache/Python-Eggs/dyNET-0.0.0-py2.7-linux-x86_64.egg-tmp/_dynet.so: undefined symbol: _ZN5dynet13TextFileSaver4saveERKNS_19ParameterCollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

Additional Info:
I run the ``python setup.py install --user'' and already tried to append ``export DYLD_LIBRARY_PATH=/path/to/dynet/build/dynet/:$DYLD_LIBRARY_PATH'' in my ~/.bashrc.

Thanks and regards,
Bill

**Comment by neubig** [comment] 2017-07-05 12:10
My guess is that you still have an old version of the DyNet 1.0 library on your system, and for some reason your program is still referencing that. Could you try setting not DYLD_LIBRARY_PATH, but also LD_LIBRARY_PATH, and make sure that the `libdynet.so` file in that directory is the appropriate version?

**Comment by weidler** [comment] 2017-07-22 22:43
I have the exact same issue. 

```
Traceback (most recent call last):
  File "xor.py", line 2, in <module>
    import dynet as dy
  File "/home/weidler/.local/lib/python3.5/site-packages/dyNET-0.0.0-py3.5-linux-x86_64.egg/dynet.py", line 17, in <module>
    from _dynet import *
ImportError: /home/weidler/.local/lib/python3.5/site-packages/dyNET-0.0.0-py3.5-linux-x86_64.egg/_dynet.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5dynet13TextFileSaver4saveERKNS_19ParameterCollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I removed anything dynet related from debian. I've set the Paths to 

```
export DYLD_LIBRARY_PATH=/home/weidler/dynet-base/dynet/build/dynet/:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/weidler/dynet-base/dynet/build/dynet/:$LD_LIBRARY_PATH
```

in my ~/.bashrc, but I still experience the same issue. I am trying to run it with GPU backend on Debian 9.

Would be nice to get some help with it.
Thanks!

**Comment by leejayyoon** [comment] 2017-09-27 18:33
Have anyone got solution to this?

I get the same kind of error.


This is the error log:
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/dynet.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/_dynet.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_dynet.py", line 6, in __bootstrap__
ImportError: /home/jisuk1/.cache/Python-Eggs/dyNET-0.0.0-py2.7-linux-x86_64.egg-tmp/_dynet.so: undefined symbol: _ZN5dynet13TextFileSaver4saveERKNS_19ParameterCollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by pmichel31415** [comment] 2017-09-27 21:28
Can you try adding this line in your `.bashrc`?

```bash
export PYTHONPATH=$PREFIX/tools/dynet-base/dynet/build/python:$PYTHONPATH
```

**Comment by leejayyoon** [comment] 2017-09-27 22:36
@pmichel31415  I tired adding it, but it didn't work. 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jisuk1/tools/dynet-base/dynet/build/python/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: /home/jisuk1/tools/dynet-base/dynet/build/python/_dynet.so: undefined symbol: _ZN5dynet13TextFileSaver4saveERKNS_19ParameterCollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by neubig** [comment] 2018-02-09 21:32
I'm not sure what the problem is here, but probably it's resolved with the recent changes to the installation script. If not, I'll re-open.

**Closed by neubig** 2018-02-09 21:32 UTC
Labels: need more info
