### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by fmacicasan** [clab/dynet#146] opened 2016-11-06 17:56 UTC
Hello,

I'm trying to install dynet on my local machine and I keep getting an error while importing dynet in python.
>import dynet as dy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dynet.py", line 17, in <module>
    from _dynet import *
ImportError: dlopen(./_dynet.so, 2): Library not loaded: @rpath/libdynet.dylib
  Referenced from: /dynet-base/dynet/build/python/_dynet.so
  Reason: image not found

I'm using:
- MBP w/ MacOS Sierra
- Eigen's default branch from bitbucket
- The latest dynet (w/ Today's commit that fixed TravisCI)
- boost 160
- python 2.7.10
- cmake 3.6.3
- make 3.81 (built for i386-apple-darwin11.3.0)

The make log also references that file
`c++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.12-intel-2.7/dynet.o -L. -L/dynet-base/dynet/build/dynet/ -L/dynet-base/dynet/build/dynet/ -ldynet -o /dynet-base/dynet/build/python/_dynet.so
ld: warning: ignoring file /dynet-base/dynet/build/dynet//libdynet.dylib, file was built for x86_64 which is not the architecture being linked (i386): /dynet-base/dynet/build/dynet//libdynet.dylib`

Could you advise?

Thanks,
Florin.

**Comment by gmulcaire** [comment] 2016-11-11 07:53
I had a similar issue: same ImportError, though the corresponding warning was different:

```
g++ -bundle -undefined dynamic_lookup -L/Users/gmulc/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/dynet.o -L. -L/Users/gmulc/dynet-base/dynet/build/dynet/ -L/Users/gmulc/anaconda/lib -L/Users/gmulc/dynet-base/dynet/build/dynet/ -ldynet -o /Users/gmulc/dynet-base/dynet/build/python/_dynet.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
ld: warning: object file (build/temp.macosx-10.6-x86_64-2.7/dynet.o) was built for newer OSX version (10.7) than being linked (10.6)
```

This seems to be because `_dynet.so` looks for `libdynet.dylib` at `@rpath/libdynet.dylib` which doesn't work unless `/path/to/dynet/build/dynet` is in `@rpath`. You can update it with `install_name_tool -change @rpath/libdynet.dylib /path/to/dynet/build/dynet/libdynet.dylib _dynet.so` (and then verify the change with `otool -L _dynet.so`).

Not sure why the shared library path is like that in the first place, but this could at least be a workaround. Hope it works for you!

**Comment by neubig** [comment] 2016-11-17 20:54
@yoavg do you think we need to add instructions about `export DYLD_LIBRARY_PATH=/path/to/dynet/build/dynet/:$DYLD_LIBRARY_PATH` to the python doc?

**Comment by yoavg** [comment] 2016-11-17 21:03
This is definitely an option. I guess the real solution is to figure out
how to fix this for all users *without* the need to specify the path (as it
works for me and many others now), but I think it is probably not worth the
effort. So I'd add something like: "on some systems, you need to specify..."

**Comment by neubig** [comment] 2016-11-21 22:20
This was probably fixed by this commit: https://github.com/clab/dynet/commit/aa03883a18d80984c02c9469058275a66e865839

**Comment by gmulcaire** [comment] 2016-11-22 23:16
[`aa03883`](https://github.com/clab/dynet/commit/aa03883a18d80984c02c9469058275a66e865839) worked for me.

**Comment by fmacicasan** [comment] 2016-11-27 13:35
I also updated to latest dynet and i managed to successfully build and import dynet in python.

Thanks!

**Comment by SimonOst** [comment] 2017-07-26 23:21
Hi, the fix you proposed is unfortunately not working for me. I am using Mac OS X and get the following error when importing: 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "build/bdist.macosx-10.12-intel/egg/dynet.py", line 17, in <module>
>   File "build/bdist.macosx-10.12-intel/egg/_dynet.py", line 7, in <module>
>   File "build/bdist.macosx-10.12-intel/egg/_dynet.py", line 6, in __bootstrap__
> ImportError: dlopen(/Users/Simon/Library/Caches/Python-Eggs/dyNET-0.0.0-py2.7-macosx-10.12-intel.egg-tmp/_dynet.so, 2): Library not loaded: /tmp/pip-build-zTAokf/dynet/build/py2.7-64bit/dynet/libdynet.dylib
>   Referenced from: /Users/Simon/Library/Caches/Python-Eggs/dyNET-0.0.0-py2.7-macosx-10.12-intel.egg-tmp/_dynet.so
>   Reason: image not found

**Comment by rilut** [comment] 2017-08-24 13:50
Me too, I installed from pip-github so I don't have my build folder anymore

```
$ python dynet-exp.py
Traceback (most recent call last):
  File "dynet-exp.py", line 20, in <module>
    import dynet as dy
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dynet.py", line 13, in <module>
    from _dynet import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_dynet.so, 2): Library not loaded: /private/var/folders/rk/5qqd_n954m5280w7k6sw0z040000gp/T/pip-build-Ke2xBw/dynet/build/py2.7-64bit/dynet/libdynet.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_dynet.so
  Reason: image not found```

**Comment by HuitingLiu** [comment] 2017-09-03 02:46
Me too, a student from 11747. try to run the example code but get the image error:
```
python bow.py 
Traceback (most recent call last):
  File "bow.py", line 4, in <module>
    import dynet as dy
  File "/Users/liuhuiting/py2venv/lib/python2.7/site-packages/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: dlopen(/Users/liuhuiting/py2venv/lib/python2.7/site-packages/_dynet.so, 2): Library not loaded: /private/var/folders/d7/fmj8dbx96kl46nkg02c_c4_m0000gn/T/pip-build-9ycG9t/dynet/build/py2.7-64bit/dynet/libdynet.dylib
  Referenced from: /Users/liuhuiting/py2venv/lib/python2.7/site-packages/_dynet.so
  Reason: image not found
```

**Comment by xunzhang** [comment] 2017-09-04 00:00
I think exporting `DYLD_LIBRARY_PATH ` should solve the problem. One thing Mac users need to pay attention to is __Disable System Integrity Protection (rootless)__ before exporting this environment variable. To verify this, try `env | grep DYLD_LIBRARY_PATH`. 

To turn off, follow below steps:
1. Boot OS X into Recovery Mode(hold down Command + R keys simultaneously after you hear the startup chime)
2. When the `OS X Utilities` screen appears, `Utilities`->`Terminal`
3. Type `csrutil disable; reboot` into the terminal then hit return.

**Comment by HuitingLiu** [comment] 2017-09-04 22:41
@xunzhang  Hi, Could you please tell me how to the /path/to/dynet/build/dynet/?

**Comment by rilut** [comment] 2017-09-04 22:48
@xunzhang  My problem is, after pip-git is building my dynet on a build folder `/private/var/folders/rk/somelongrandomname/T/pip-build-LRuDhC/dynet`, it deletes the build folder itself. and `--no-clean` flag is seems to be broken [[1]](https://stackoverflow.com/questions/45866468/how-to-do-pip-installation-from-github-without-removing-the-source-folder)[[2]](https://github.com/pypa/pip/issues/3171)

**Comment by HuitingLiu** [comment] 2017-09-04 22:50
In my case, I install the dynet by pip within a virtual environment. And the export command is: `export DYLD_LIBRARY_PATH=/Users/xxx/py2venv/lib/:$DYLD_LIBRARY_PATH`

**Comment by neubig** [comment] 2017-09-06 02:57
I was able to confirm this problem when performing install with `pip`+`anaconda` and was able to solve it using using the following command:

    export DYLD_LIBRARY_PATH="/Users/XXX/anaconda/envs/YYY/lib/:$DYLD_LIBRARY_PATH"

where XXX is your username, and YYY is the name of the environment. This temporary workaround should work, but we really need to find a more permanent fix (FYI @danielhers and @xunzhang)

**Comment by everdark** [comment] 2017-09-10 04:13
Same issue here.
I use
```
BACKEND=cuda pip3 install git+https://github.com/clab/dynet#egg=dynet
```
to install and no error produced during installation.
However when trying `import dynet` in python I got `ImportError`

There is no build folder since it is in temp and is deleted after a "successful" installation, so i just can't set `DYLB_LIBRARY_PATH` to the location of `libdynet.dylib` (which indeed does not exist in my system at all after the installation)

i dont use conda so it is also not a solution in the first place.

My system info:
```
macos 10.12.4
python 3.6.1
```

Btw I also can not install dynet by the manual installation guide.
It seems to be some path issue complaining lots of `*.h` files not found. 
Not yet dig into it though.

**Comment by danielhers** [comment] 2017-09-10 05:49
This should certainly be fixed, but there are several root causes for this problem - when installing by `pip install dynet`, there was a brief period last week where the pre-compiled macOS wheels were taken, and they just didn't have `libdynet.dylib` in them. I fixed this by removing them, so DyNet is built during the installation again, just like when installing from `master` by `pip install git+https://github.com/clab/dynet#egg=dynet`. However, when installing like that, `libdynet.dylib` is supposed to be copied to `lib/` under the current Python installation, as @neubig said. If it's not, that's a bug and should be fixed.

**Comment by danielhers** [comment] 2017-11-06 13:23
This should no longer happen when installing with `pip install dynet`.

**Comment by venkatasg** [comment] 2017-12-01 22:31
```libdynet.dylib``` is present in ```lib/```, but I'm still getting the same error. It doesn't seem to be look for the file in that location. How to fix?

**Comment by danielhers** [comment] 2017-12-02 06:10
@venkatasg how did you install dynet?
Did you try in a new virtualenv?

**Comment by venkatasg** [comment] 2017-12-02 15:17
Initially I was installing it using my macport pip and python but I never got it to work. I tried with anaconda and it finally worked!

**Closed** 2018-02-09 21:18 UTC
Labels: moderate bug
