### ISSUE TITLE
Weird EIGEN Error While Installing PyCnn V2.0

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#78] opened 2016-09-18 11:12 UTC
Hi, I'm trying to install PyCnn 2.0 on MacOS
This is the error I'm getting:

/Users/talbaumel/cnn/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorChipping.h:152:5: error: 
      static_assert failed "YOU_MADE_A_PROGRAMMING_MISTAKE"
    EIGEN_STATIC_ASSERT(NumInputDims >= 2, YOU_MADE_A_PROGRAMMING_MISTAKE);
    ^                   ~~~~~~~~~~~~~~~~~
/Users/talbaumel/cnn/eigen/Eigen/src/Core/util/StaticAssert.h:32:40: note: 
      expanded from macro 'EIGEN_STATIC_ASSERT'
    #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                       ^             ~
/Users/talbaumel/cnn/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorEvaluator.h:323:7: note: 
      in instantiation of member function 'Eigen::TensorEvaluator<const
      Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<float, 1,
      0, long>, 0> >, Eigen::DefaultDevice>::TensorEvaluator' requested here
      m_rightImpl(op.rhsExpression(), device)
      ^
/Users/talbaumel/cnn/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:102:7: note: 
      in instantiation of member function 'Eigen::TensorEvaluator<const
      Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float>,
      const Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>, 0>, const
      Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<float, 1,
      0, long>, 0> > >, Eigen::DefaultDevice>::TensorEvaluator' requested here
      m_rightImpl(op.rhsExpression(), device)
      ^
/Users/talbaumel/cnn/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:56:48: note: 
      in instantiation of member function 'Eigen::TensorEvaluator<const
      Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>,
      0>, const
      Eigen::TensorCwiseBinaryOpEigen::internal::scalar_difference_op<float,
      const Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>, 0>, const
      Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<float, 1,
      0, long>, 0> > > >, Eigen::DefaultDevice>::TensorEvaluator' requested here
    TensorEvaluator<Expression, DefaultDevice> evaluator(expr, device);
                                               ^
/Users/talbaumel/cnn/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDevice.h:35:59: note: 
      in instantiation of member function 'Eigen::internal::TensorExecutor<const
      Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>,
      0>, const
      Eigen::TensorCwiseBinaryOpEigen::internal::scalar_difference_op<float,
      const Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>, 0>, const
      Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<float, 1,
      0, long>, 0> > > >, Eigen::DefaultDevice, true>::run' requested here
      internal::TensorExecutor<const Assign, DeviceType>::run(assign, m_device);
                                                          ^
/Users/talbaumel/cnn/cnn/nodes.cc:1377:38: note: in instantiation of function
      template specialization
      'Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>,
      0>,
      Eigen::DefaultDevice>::operator=Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float,
      const Eigen::TensorMap<Eigen::Tensor<float, 0, 0, long>, 0>, const
      Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<float, 1,
      0, long>, 0> > > >' requested here
      fx.t<0>().device(_dev.edevice) = z.t<0>() - xs[0]->t<1>().chip<0>(_pval);

**Comment by neubig** [comment] 2016-09-18 11:44
I wasn't able to reproduce this with the latest version of Eigen and cnn on El Capitan. Would you mind providing the version numbers of eigen, cnn, clang, and cnn v2?

**Comment by talbaumel** [comment] 2016-09-18 11:52
I'm using Sierra, it might have something to do with that
All other libraries are also the latest

**Comment by talbaumel** [comment] 2016-09-19 11:37
I tried installing pycnn V1 from scratch, the CPU went smoothly
After executing:

cmake .. -DBACKEND=cuda -DCUDA_TOOLKIT_ROOT_DIR=/Developer/NVIDIA/CUDA-7.5/
make -j 4

I got the following errors:

make[2]: *** [cnn/CMakeFiles/cnncuda_shared.dir/cnncuda_shared_generated_gpu-ops.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at cnncuda_generated_gpu-ops.cu.o.cmake:263 (message):
  Error generating file
  /Users/talbaumel/cnn/build/cnn/CMakeFiles/cnncuda.dir//./cnncuda_generated_gpu-ops.cu.o


make[2]: *** [cnn/CMakeFiles/cnncuda.dir/cnncuda_generated_gpu-ops.cu.o] Error 1
make[1]: *** [cnn/CMakeFiles/cnncuda.dir/all] Error 2
/usr/include/stdio.h(133): error: expected a ")"

/usr/include/stdio.h(134): error: expected a ")"

/usr/include/stdio.h(134): error: "_Nullable" has already been declared in the current scope

/usr/include/stdio.h(135): error: expected a ")"

/usr/include/stdio.h(135): error: "_Nullable" has already been declared in the current scope

/usr/include/stdio.h(136): error: expected a ")"

/usr/include/stdio.h(136): error: "_Nullable" has already been declared in the current scope

/usr/include/stdio.h(477): error: duplicate parameter name

/usr/include/stdio.h(478): error: duplicate parameter name

/usr/include/stdio.h(479): error: duplicate parameter name

/usr/include/stdlib.h(139): error: expected a ")"

/usr/include/stdlib.h(158): error: expected a ")"

/usr/include/stdlib.h(294): error: expected a ")"

/usr/include/stdlib.h(300): error: expected a ")"

/usr/include/stdlib.h(306): error: expected a ")"

/usr/include/stdlib.h(312): error: expected a ")"

/usr/include/stdlib.h(318): error: expected a ")"

17 errors detected in the compilation of "/var/folders/fr/6yxg1k8j1xsfd5v3b4z20c480000gn/T//tmpxft_000040c3_00000000-22_gpu-ops.compute_52.cpp1.ii".
CMake Error at cnncuda_generated_gpu-ops.cu.o.cmake:263 (message):
  Error generating file
  /Users/talbaumel/cnn/build/cnn/CMakeFiles/cnncuda.dir//./cnncuda_generated_gpu-ops.cu.o

**Comment by neubig** [comment] 2016-09-20 20:57
v1 will be deprecated very soon so I'll focus on v2. I don't have sierra at hand, but once I get my hands on a sierra machine I can try to debug. Of course, if you fix the problem yourself a patch would be appreciated.

**Comment by neubig** [comment] 2016-11-28 20:07
@talbaumel Is this issue resolved now? If so, can you close it?

**Comment by talbaumel** [comment] 2016-11-28 21:47
I installed the latest DyNet version using this manual (http://dynet.readthedocs.io/en/latest/python.html) on the os x 10.12

The CPU version worked great
The GPU version didn't (CUDA installed and using  GeForce GT 750M) 
Same machine is running Theano with GPU support

I can recreate the error but I don't think it's readable

Btw, on my mac while following the instructions I had to change the eigen path when compiling

**Comment by neubig** [comment] 2016-11-28 21:51
Hmm, OK. Thanks for checking anyway. This'll have to wait until someone else can replicate, but my Mac doesn't have an nvidia GPU so we're stuck for now.

**Comment by neubig** [comment] 2017-02-16 03:03
CUDA seems to be working on OSX since this: https://github.com/clab/dynet/pull/305

Are things working now?

**Comment by talbaumel** [comment] 2017-02-17 15:40
I updated CUDA and it didn't work

btw, the cmake line in the documantation should be:
cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=`which python` -DBACKEND=cuda
intead of:
cmake .. -DEIGEN3_INCLUDE_DIR=../eigen -DPYTHON=`which python` -DBACKEND=cuda

**Comment by neubig** [comment] 2017-02-17 15:52
Sorry, not updating CUDA, updating DyNet. Are you using the most recent version from master? And thanks for pointing out the error with the Eigen path.

**Comment by talbaumel** [comment] 2017-02-17 16:04
Yeah, I tried to install the latest version

Thank you for the support and the great library!

**Comment by neubig** [comment] 2017-07-14 11:40
Just checking regularly, has this been resolved with the latest version? I've seen this bug reported one other time but never have been able to reproduce it myself.

**Closed** 2017-07-16 09:14 UTC
Labels: need more info
