### ISSUE TITLE
Saveable subclasses trying to save Model

### ISSUE THREAD

**Issue by nsaphra** [clab/dynet#237] opened 2017-01-13 11:43 UTC
Is this intended behavior?

Shouldn't Model just be ignored?

If I include the model as an attribute of a Saveable subclass, even when it is not included in get_components, it throws an error indicating that it is attempting to save the model anyway.

Traceback:
```
Traceback (most recent call last):
  File "/disk/scratch/nsaphra/dynamic_curriculum//model_save_bug.py", line 21, in <module>
    m.save("fail.model", [lm])
  File "_gdynet.pyx", line 353, in _gdynet.Model.save (_gdynet.cpp:11640)
  File "_gdynet.pyx", line 339, in _gdynet.Model._save_one (_gdynet.cpp:11170)
  File "/disk/scratch/nsaphra/bin/miniconda2/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle Model objects
```

Minimal example:
```python
from dynet import *

class LanguageModel(Saveable):
    def __init__(self, model):
        self.model = model
        self.lookup = model.add_lookup_parameters((1000,10))

    def get_components(self):
        return (self.lookup,)

    def restore_components(self, components):
        raise NotImplemented

if __name__ == '__main__':
    m = Model()
    lm = LanguageModel(m)
    m.save("fail.model", [lm])
```

**Comment by yoavg** [comment] 2017-01-13 12:25
Thanks!

This is currently both the intended behavior **and** an annoying bug (or at least a confusing behavior).

The way saving works is by:
- components (returned by `get_components`) are handled by the dynet loading/saving mechanism.
- **everything else** (things in the object's dict) is handled by python's pickling mechanism (components are specifically removed from the pickling in `__getstate__` of saveable because they are not saveable)

I guess what we need is a mechanism for things that are part of the object, are not parameters/components, but should not be pickled. One way to add this is an `ignore_fields` method in `Saveable`, and then remove these things in `__getstate__`. (and maybe there is more "standard" name for this method in the pickle protocol?)
If you add this and do some minimal testing (and document it?) I will happily approve the PR
(or I can get to it at some point in the future).

One question though, is how were you planning to later on load this saved object? Support for this could be nice also.

**Comment by yoavg** [comment] 2017-01-13 12:44
Actually, upon more thought, I think the proper way to address this in Python would be to have your own class have its own __getstate__ method that will first call the Saveable __getstate__ and then remove whatever else there is to be removed. And this should probably be documented.

**Comment by neubig** [comment] 2017-04-07 20:45
This will be fixed by the upcoming interface: https://github.com/clab/dynet/issues/84

**Comment by neubig** [comment] 2017-06-29 01:39
This should be fixed by https://github.com/clab/dynet/pull/637

**Closed by neubig** 2017-06-29 01:39 UTC
Labels: moderate bug
