### ISSUE TITLE
Setting dynet memory in jupyter notebook, using an API

### ISSUE THREAD

**Issue by napsternxg** [clab/dynet#255] opened 2017-01-17 21:16 UTC
I couldn't find a way to set the memory of dynet in jupyter notebook. I have resorted to the following hack:
```
import sys

try:
    __file__
except:
    sys.argv = [sys.argv[0], '--dynet-mem', '10000']

"""
Outputs:
[dynet] random seed: 2618859252
[dynet] allocating memory: 10000MB
[dynet] memory allocation done.
"""
```

Is there a better way to set the memory while working from the notebook?

**Comment by pmichel31415** [comment] 2017-01-18 21:40
Hi,

I'm working on making this available like in the c++ code, expect a pull request by tomorrow if everything goes well.

**Comment by RobRomijnders** [comment] 2017-02-01 15:41
How did this end up

**Comment by pmichel31415** [comment] 2017-02-01 15:53
Hi I did a pull request regarding this ( #258 ) but it's still waiting for @yoavg 's approval.

If it's urgent you can clone directly my branch https://github.com/pmichel31415/dynet/tree/python_params (I just put it up to date with the master branch)

**Comment by RobRomijnders** [comment] 2017-02-01 16:14
Thanks, trying that now

**Comment by RobRomijnders** [comment] 2017-02-01 16:21
I'm getting AttributeError

`AttributeError: 'module' object has no attribute DynetParams`

**Comment by pmichel31415** [comment] 2017-02-01 16:25
Hmm weird it works for me. Have you tried running it from the build/python folder of this fork? If it works then it's probably because your  environment variables point to the master branch

**Comment by RobRomijnders** [comment] 2017-02-01 16:27
Thanks for the fast responses!
How would that work? Both 
`git clone https://github.com/pmichel31415/dynet/tree/python_params` and
`git clone https://github.com/pmichel31415/dynet/tree/python_params.git` 
result in errors for me.

So I ended up doing
`git clone https://github.com/pmichel31415/dynet.git`

**Comment by pmichel31415** [comment] 2017-02-01 16:30
Oh ok i thought it would clone the branch directly my bad.

Then

    git clone https://github.com/pmichel31415/dynet.git
    git checkout python_params

Or maybe

    git clone -b python_params https://github.com/pmichel31415/dynet.git

should do the trick

**Comment by RobRomijnders** [comment] 2017-02-01 16:31
Checking that now:)

**Comment by RobRomijnders** [comment] 2017-02-01 17:06
Works! Thank you!

**Comment by pmichel31415** [comment] 2017-02-01 18:30
Great. If you ever have the opportunity to test the gpu parameters, let me know if they work, I currently don't have access to a gpu.

**Comment by RobRomijnders** [comment] 2017-02-01 21:11
Sure, I'm happy to help too. How could I test that?

**Comment by pmichel31415** [comment] 2017-02-01 22:17
I think running a simple example (like linear regression) with `dyparams.set_requested_gpus(1)`with a GPU enabled build and check that the GPU is actually used would be sufficient.

**Comment by neubig** [comment] 2017-02-16 02:37
Should be fixed with this: https://github.com/clab/dynet/pull/258

**Closed by neubig** 2017-02-16 02:37 UTC
