### ISSUE TITLE
More comments and documents

### ISSUE THREAD

**Issue by MalcolmSun** [clab/dynet#94] opened 2016-10-11 07:05 UTC
Hi, I'm interested in this project. Unfortunately, because of the lack of code comments, I have to spend much time understanding the code. I do hope the project can have more comments in code files and more complete documents which can help others have a general understanding of the project.
Thanks in advance.

**Comment by neubig** [comment] 2016-10-11 12:09
Hi @MalcolmSun, thanks for sending the issue! We certainly agree, but this is a duplicate of https://github.com/clab/dynet/issues/85
We're going to start with commenting all the functions that people can use.

**Closed by neubig** 2016-10-11 12:09 UTC
