### ISSUE TITLE
"pip uninstall dynet"  try to delete root!   ####   ERROR：shutil.Error: Destination path '/tmp/pip-96n6re9_-uninstall/' already exists

### ISSUE THREAD

**Issue by wywzxxz** [clab/dynet#1266] opened 2018-03-02 08:45 UTC
when I tried to uninstall dynet, an error occured:

> ERROR：shutil.Error: Destination path '/tmp/pip-96n6re9_-uninstall/' already exists

It's so confused that shutil.move throw an error about folder exist that the destination should exist as it designed( in this case it should move all file form src to destination folder.)

The real reason about the error should be : the destination floder had been occupied! In my case, pip tried to move /(root floder) to  it's child(/tmp/pip-96n6re9-uninstall).  

Here is debug output. I tracked UninstallSetPath.add, print paths added to It. I believe those path well evently be deleted. 

> wuyuewan debug: path_to_remove <pip.req.req_uninstall.UninstallPathSet object at 0x7fe2213de668> dyNET 0.0.0
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dynet.py
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/__pycache__/dynet.cpython-35.pyc
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dynet_viz.py
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/__pycache__/dynet_viz.cpython-35.pyc
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dynet_config.py
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/__pycache__/dynet_config.cpython-35.pyc
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/__pycache__/dynet.cpython-35.pyc
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/__pycache__/dynet_viz.cpython-35.pyc
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/__pycache__/dynet_config.cpython-35.pyc
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/_dynet.cpython-35m-x86_64-linux-gnu.so
> **wuyuewan debug UninstallSetPath add /**
> **wuyuewan hot fix: UnInstallPathSet should not receive / (the root)**
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info/dependency_links.txt
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info/SOURCES.txt
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info/top_level.txt
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info/PKG-INFO
> wuyuewan debug UninstallSetPath add /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info/requires.txt
> wuyuewan debug: path_to_remove= UninstallPathset(dist) <pip.req.req_uninstall.UninstallPathSet object at 0x7fe2213de668>
> Uninstalling dyNET-0.0.0:
>   /usr/local/lib/python3.5/dist-packages/__pycache__/dynet.cpython-35.pyc
>   /usr/local/lib/python3.5/dist-packages/__pycache__/dynet_config.cpython-35.pyc
>   /usr/local/lib/python3.5/dist-packages/__pycache__/dynet_viz.cpython-35.pyc
>   /usr/local/lib/python3.5/dist-packages/_dynet.cpython-35m-x86_64-linux-gnu.so
>   /usr/local/lib/python3.5/dist-packages/dyNET-0.0.0-py3.5.egg-info
>   /usr/local/lib/python3.5/dist-packages/dynet.py
>   /usr/local/lib/python3.5/dist-packages/dynet_config.py
>   /usr/local/lib/python3.5/dist-packages/dynet_viz.py
> Proceed (y/n)? y
> 

Here is the output without debug and hot fix

> Uninstalling dyNET-0.0.0:
>   /
> Proceed (y/n)? y 

Yes, shows only the root folder, I don't know why 

I don't know what happend, I can't repoduce it yet. As far as I know, I didn't build dynet from source, just install if from pip2/pip3 or apt-get.

This is most an reminder about "shutil.Error: Destination path already exists" to someone encount it, as I find no solution on internet. 
Here's the fix:
open `/local/lib/python3.5/dist-packages/pip/req/req_uninstall.py` ,find  `def add(self,path):` , add above 3 line below:

`     if path=="/" `
`          print("hot fix: UninstallPathSet shouldn't add / (the root) ") `
`          return`

Also I think I should report this since it tried to do an dangerous opertaion. However since I have no idea why it happens and  can't repoduce it, close this issue if you want.

**Comment by neubig** [comment] 2018-03-23 13:11
Thanks for reporting, but it'll be quite difficult for us to debug if we can't reproduce. I'll close the issue, but if you can come up with a more consistent way to reproduce this we'll be happy to fix it.

**Closed by neubig** 2018-03-23 13:11 UTC

**Comment by liaocs2008** [comment] 2018-05-10 16:56
I have seen this problem as well. Any ideas how to fix it?

**Comment by wywzxxz** [comment] 2018-05-14 09:28
@liaocs2008 
open /local/lib/python3.5/dist-packages/pip/req/req_uninstall.py ,find def add(self,path): , add above 3 line below:
if path=="/"
print("hot fix: UninstallPathSet shouldn't add / (the root) ")
return
