### ISSUE TITLE
Latest document was injected for some reason.

### ISSUE THREAD

**Issue by xunzhang** [clab/dynet#1275] opened 2018-03-08 19:11 UTC
http://dynet.readthedocs.io/en/latest/python_ref.html

**Comment by pmichel31415** [comment] 2018-03-08 19:31
I think I've identified the error I'm working on a fix. In the meantime I've made sure that http://dynet.readthedocs.io redirects to the 2.0.3 documentation

**Comment by pmichel31415** [comment] 2018-03-08 20:02
OK it seems that sphinx was complaining because the Parameters class was defined above its parent class Expression, I've reordered things and it should work now, I'll close this issue as soon as I've confirmed that the doc is fixed.

**Closed** 2018-03-08 20:26 UTC
