### ISSUE TITLE
Memory used by the computation graph

### ISSUE THREAD

**Issue by smar111** [clab/dynet#1031] opened 2017-10-29 23:04 UTC
Hi. So my program (in C++) runs out of memory on the GPU after a few hours of runtime. I want to know if there is any way to find out how much memory is being used by the computation graph, for instance, for a few sentences/minibatch in my training data?

**Comment by chunyang-wen** [comment] 2017-10-31 05:25
It seems that it is on the working list and logged [here](https://github.com/clab/dynet/issues/498)

**Comment by neubig** [comment] 2017-11-05 10:57
Yes, this is important, but it's a duplicate of #498

**Closed by neubig** 2017-11-05 10:57 UTC
Labels: duplicate
